version: 2.1
orbs:
  browser-tools: circleci/browser-tools@1.5.3

jobs:
  audit:
    docker:
      - image: cimg/node:lts
    steps:
      - checkout
      - run: npm ci
      - run: npm audit signatures

  test:
    docker:
      - image: cimg/node:lts-browsers
    steps:
      - browser-tools/install-chrome
      - browser-tools/install-firefox
      - checkout
      - run: npm ci
      - run: npm run test

workflows:
  version: 2
  ci:
    jobs:
      - audit
      - test
