version: 2.1

jobs:
  audit:
    docker:
      - image: cimg/node:lts
    steps:
      - checkout
      - run: npm ci
      - run: npm audit signatures

  test:
    docker:
      - image: cimg/node:lts
    steps:
      - checkout
      - run: npm ci
      - run: npx playwright install --with-deps
      - run: npm run test

workflows:
  version: 2
  ci:
    jobs:
      - audit
      - test
